### ISSUE TITLE
Automatically install requirements per indexer

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/executor-indexers#51]
Use a logic like

`git+https://github.com/jina-ai/executor-indexers#egg=executor-indexers[postgres]`
`git+https://github.com/jina-ai/executor-indexers#egg=executor-indexers[lmdb]`
`git+https://github.com/jina-ai/executor-indexers#egg=executor-indexers[annoy]`
etc.

**Comment by CatStark** [comment]
Moved to https://github.com/jina-ai/executors/issues/5
