### ISSUE TITLE
Hub mono-repo

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/executor-indexers#76]
Move all Executors into one repository

Name: `executors`

CI:

- test locally (only on change)
- integration tests run together 

CD:
- push to Hub based on secrets (stored in repo secrets). TODO. come with scalable solution here (maybe download gdrive sheet)

Jina version management:
- TBD

**Comment by CatStark** [comment]
Moved to https://github.com/jina-ai/executors/issues/4
